import type { Metadata } from 'next';
import React from 'react';
import { Ubuntu, Titillium_Web } from 'next/font/google';
import Navbar from '../../components/Navbar';
import './globals.css';
import { NextIntlClientProvider, useMessages } from 'next-intl';

const ubuntu = Ubuntu({ weight: ['300', '400'], subsets: ['latin'] });
const titillium = Titillium_Web({
  weight: ['300', '400', '900', '200'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'davorDev',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: { locale: 'en' | 'es' };
};

// Can be imported from a shared config
const locales = ['en', 'es'];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

const RootLayout: React.FC<Props> = ({ children, params: { locale } }) => {
  const messages = useMessages();
  return (
    <html lang={locale} className='w-screen h-full bg-delftBlue'>
      <body className={titillium.className}>
        <div className='absolute pointer-events-none inset-0 -z-40 h-full bg-[url("/noisetexture.jpg")] opacity-20 mix-blend-soft-light'></div>
        <NextIntlClientProvider messages={messages}>
          <div className='h-24'>{/* <Navbar /> */}</div>
          <div className='md:h-[calc(100vh-6rem)]'>{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
